// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnEuVzukyZBUOjpByeeYFcV8ecpvlKjXI',
    appId: '1:13565609507:web:6c5692b90e4efa1c731396',
    messagingSenderId: '13565609507',
    projectId: 'doandidong-82fe3',
    authDomain: 'doandidong-82fe3.firebaseapp.com',
    databaseURL: 'https://doandidong-82fe3-default-rtdb.firebaseio.com',
    storageBucket: 'doandidong-82fe3.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_jAqivk2yQfZewTMLcnADTyzX2S6iiFo',
    appId: '1:13565609507:android:06bbebbd49730b4e731396',
    messagingSenderId: '13565609507',
    projectId: 'doandidong-82fe3',
    databaseURL: 'https://doandidong-82fe3-default-rtdb.firebaseio.com',
    storageBucket: 'doandidong-82fe3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDstF_VyaCpq85nCAN0cr20E3gOZOKl-OI',
    appId: '1:13565609507:ios:047010a7f4c4d8ca731396',
    messagingSenderId: '13565609507',
    projectId: 'doandidong-82fe3',
    databaseURL: 'https://doandidong-82fe3-default-rtdb.firebaseio.com',
    storageBucket: 'doandidong-82fe3.firebasestorage.app',
    iosBundleId: 'com.example.doancuoiki',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDstF_VyaCpq85nCAN0cr20E3gOZOKl-OI',
    appId: '1:13565609507:ios:047010a7f4c4d8ca731396',
    messagingSenderId: '13565609507',
    projectId: 'doandidong-82fe3',
    databaseURL: 'https://doandidong-82fe3-default-rtdb.firebaseio.com',
    storageBucket: 'doandidong-82fe3.firebasestorage.app',
    iosBundleId: 'com.example.doancuoiki',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnEuVzukyZBUOjpByeeYFcV8ecpvlKjXI',
    appId: '1:13565609507:web:120ab20a787c4327731396',
    messagingSenderId: '13565609507',
    projectId: 'doandidong-82fe3',
    authDomain: 'doandidong-82fe3.firebaseapp.com',
    databaseURL: 'https://doandidong-82fe3-default-rtdb.firebaseio.com',
    storageBucket: 'doandidong-82fe3.firebasestorage.app',
  );
}
